version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    image: deathtoalllive/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    image: deathtoalllive/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: deathtoalllive/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
    volumes:
      - static:/static
      - media:/media
    ports:
      - 8080:80
