version: '3.3'

volumes:
  static:
  pg_data:
  backend_static:
  backend_media:
  
services:
  db:
    image: postgres:15.2
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend/
    env_file: .env
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    depends_on:
      - db
  frontend:
    build: ../frontend/
    volumes:
      - static:/app/result_build
    depends_on:
      - db
  nginx:
    image: nginx:1.22.1
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
