version: '3'

volumes:
  static:
  backend_static:
  backend_media:
  pg_data:

services:
  db:
    image: postgres:15.2
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    image: deathtoalllive/foodgram_backend
    env_file: .env
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media

  frontend:
    image: deathtoalllive/foodgram_frontend
    env_file: .env
    volumes:
      - static:/app/result_build

  nginx:
    image: nginx:1.22.1
    env_file: .env
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ../docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 8080:80
