# Generated by Django 3.2.20 on 2023-10-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20231028_1628'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_ingredients',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique_combination',
        ),
    ]
