# Generated by Django 3.2.20 on 2023-10-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportIngredient',
        ),
    ]
