# Generated by Django 3.2.20 on 2023-11-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_importingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTag',
            fields=[
                ('importingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.importingredient')),
            ],
            bases=('recipes.importingredient',),
        ),
    ]
