# Generated by Django 3.2.20 on 2023-11-06 15:16

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20231103_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Количество ингредиентов не может быть меньше 1'), django.core.validators.MaxValueValidator(30000, message='Количество ингредиентов не может быть больше 30000')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#ffd057', error_messages={'unique': 'Такой цвет уже существует.'}, image_field=None, max_length=7, samples=None, unique=True, verbose_name='Цвет в HeX'),
        ),
    ]
